### ISSUE TITLE
ckfinder not working - nginx error

### ISSUE THREAD

**Issue by le-zell** [martialblog/docker-limesurvey#133]
``using nginx + docker 5.4.10 version

When accessing to "browse the server" to upload images for example.

The page on URI : <hostname>/third_party/kcfinder/browse.php?type=images&CKEditor=description_fr&CKEditorFuncNum=2&langCode=fr has missing js and css files witch are rendered by css/index.php and js/index.php files.

in logs we have nginx errors : 
```
rewrite or internal redirection cycle while internally redirecting to "index.php"
```

maybe an nginx error configuration

**Comment by martialblog** [comment]
Hi, could this be related to the issue #131 ? There also was some mentioning of the ckfinder plugin.

My first instinct is to thing about the BASE_URL and PUBLIC_URL parameters. However, there are also issues reported with the app not playing nicely with reverse proxies regardless of the parameters. Could be related. 

Regards

**Comment by le-zell** [comment]
Yes i think so.

It's maybe relative to a config parameter `''urlFormat' => 'path',` witch shortcuts the URIs...don't know...

as a workaround i hacked `third_party/kcfinder/tpl/tpl_browser.php` and put `<base href="/third_party/kcfinder/">` instead of `<base href="<?= Yii::app()->request->getBaseUrl() ?>/">` 

I get a more fonctionnal webpage (with css/js resources). But the module is not working better...

**Comment by martialblog** [comment]
There's probably a way to tell the Yii::app that it is running behind a proxy, so that the routing is handled correctly.

**Comment by bovender** [comment]
I cannot get it to work either.

The 500 error reported at the top of this issue seems to be an nginx server config issue. The nginx config files has a `location ~ \.php$ {...}` directive which contains the line `try_files $uri /index.php`. When I change this to `try_files $uri /index.php?$argsi`, the 500 error no longer occurs, but a 404 error occurs instead. And in my opinion this is the root of the problem:

Script `/vendor/kcfinder/browse.php` attempts to access the following files:

- `index.php`
- `css.php`
- `js_localize.php`
- `js.php`

All of these throw a 404 error, because `browse.php` references them in the _root_ folder (example.com/), but in fact they reside in `/vendor/kcfinder`. It's not so much about the server domain, it's the path prefix that is missing.

I see this with @martialblog's LimeSurvey 6.x as well as 5.x images.

What puzzles me is that the LimeSurvey image by @adamzammit does _not_ exhibit this behavior. I tried to find out what the differences are between the images by @martialblog and @adamzammit, but I was unable to see anything that might be relevant (e.g., different configuration or so).

This is what the 'ressources' page of a survey looks like in my browser with @martialblog 's image (the buttons are not functional):

![image](https://github.com/martialblog/docker-limesurvey/assets/1484759/ba50a301-d6f1-4ea9-af95-b0afaec546e6)

And this is a screenshot of LimeSurvey running in a container based on @adamzammit's image (buttons are functional):

![image](https://github.com/martialblog/docker-limesurvey/assets/1484759/681a533f-205e-4c0b-961e-1f5f0d7f2d0d)

To summarize, there seems to be a directory issue with the kcfinder plugin in this image.

**Comment by bovender** [comment]
P.S. Here's a `docker-compose.yml` file that helps to quickly try out the two different images:

<details><summary>(expand)</p>
</summary><p>

```yaml
version: '2'

services:

  adamzammit:
    image: adamzammit/limesurvey
    ports:
      - 127.0.0.1:9090:80
    environment:
      LIMESURVEY_DB_PASSWORD: example
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: admin
      LIMESURVEY_ADMIN_NAME: Admin
      LIMESURVEY_ADMIN_EMAIL: admin@example.com
    depends_on:
      - mysql

  martialblog:
    image: docker.io/martialblog/limesurvey:latest
    environment:
      - DBENGINE=InnoDB
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PASSWORD=example
      - DB_NAME=martialblog
      - DB_USERNAME=root
      - ADMIN_USER=admin
      - ADMIN_NAME=Admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL=foobar.com
    ports:
      - 127.0.0.1:9091:8080
    depends_on:
      - mysql

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
``` 

</p></details>

Start up these services in the usual way, invoke http://localhost:9090/admin and http://localhost:9091/admin, log in with admin/admin, quickly create new surveys, and go to the 'Resources' page to see whether ckfinder works or does not work.
