### ISSUE TITLE
Default login not working?

### ISSUE THREAD

**Issue by slhck** [martialblog/docker-limesurvey#18]
I had troubles overwriting the default login, whatever I specified in the admin password didn't work.

I am using this docker-compose file:

```
version: "3.0"
services:
  limesurvey:
    build:
      context: apache/
      dockerfile: Dockerfile
    volumes:
      - ./upload/:/var/www/html/upload/
    links:
      - lime-db
    depends_on:
      - lime-db
    ports:
      - "8080:80"
    environment:
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=secret"
      - "PUBLIC_URL=https://survey.example.com"
    restart: unless-stopped
  lime-db:
    image: mysql:5.7
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/mysql
```

I am starting everything with `docker-compose up`.

When I print the environment variables in `entrypoint.sh` (e.g. by `echo`ing them), I see:

```
limesurvey_1  | DB_TYPE=mysql
limesurvey_1  | DB_HOST=lime-db
limesurvey_1  | DB_PORT=3306
limesurvey_1  | DB_SOCK=
limesurvey_1  | DB_NAME=limesurvey
limesurvey_1  | DB_TABLE_PREFIX=lime_
limesurvey_1  | DB_USERNAME=limesurvey
limesurvey_1  | DB_PASSWORD=secret
limesurvey_1  | ADMIN_USER=admin
limesurvey_1  | ADMIN_NAME=admin
limesurvey_1  | ADMIN_EMAIL=foobar@example.com
limesurvey_1  | ADMIN_PASSWORD=-
limesurvey_1  | PUBLIC_URL=https://survey.example.com
limesurvey_1  | URL_FORMAT=path
limesurvey_1  | Info: Generating config.php
limesurvey_1  | Info: Using MySQL configuration
```

Notice the password being just `-` for the admin. I think this is a bug?

Even when I try to login with `admin` and `-` as user/password in the newly setup container, I get:

![image](https://user-images.githubusercontent.com/582444/60725773-35244600-9f3a-11e9-9d19-36756afc7e60.png)
