### ISSUE TITLE
SQL error while saving questions

### ISSUE THREAD

**Issue by dom6770** [martialblog/docker-limesurvey#182]
I just set up limesurvey with this docker-compose.yaml:

```
version: '3'

services:
  limesurvey:
    image: docker.io/martialblog/limesurvey:6-apache
    container_name: limesurvey
    
    restart: unless-stopped
    depends_on:
      - postgres
    
    ports:
      - 7090:8080

    environment:
      - DB_TYPE=pgsql
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_PASSWORD=asdf
      - DB_NAME=limesurvey
      - DB_USERNAME=limesurvey
      - ADMIN_USER=Administrator
      - ADMIN_NAME=Administrator
      - ADMIN_PASSWORD=asdf
      - ADMIN_EMAIL=admin@sonn.intern
      - PUBLIC_URL=https://survey.example.org/

    volumes:
      - ./data:/var/www/html/upload/surveys

  postgres:
    image: docker.io/postgres:10-alpine
    container_name: limesurvey_postgres
    
    restart: unless-stopped

    environment:
      - POSTGRES_USER=limesurvey
      - POSTGRES_DB=limesurvey
      - POSTGRES_PASSWORD=asdf
    
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  limesurvey:
    name: limesurvey

```

Login in to the backend works fine, but when add a new question with an array and quick add subquestions and try to save that, the following error appears

`CDbCommand failed to execute the SQL statement: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "new64190" LINE 1: ...ELECT * FROM "lime_questions" "t" WHERE "t"."qid"='new64190'... ^`
