### ISSUE TITLE
Timings not being saved

### ISSUE THREAD

**Issue by appreciated** [martialblog/docker-limesurvey#29]
Hi there, 
first of all thank you very much for providing this docker solution for Lime Survey 🙏! 
I setup a docker-compose as shown below and all seems to be working fine. Just today it was noted that the timestamps seem not to be saved into the datasbase, even though activated in the questionaire. 

So when exporting the questions later on the timings are all empty. I looked up in the database also no timings save here all filled with `NULL`.

Do you have a clues what might cause the issues here and how to fix it?

The used docker-compose file:
```
services:
  limesurvey:
    image: martialblog/limesurvey
    container_name: limesurvey
    environment:
      DB_HOST: lime-db
      DB_PASSWORD: ${MYSQL_PASSWORD}
      ADMIN_USER: admin
      ADMIN_PASSWORD: ${LIMESURVEY_PASSWORD}
      ADMIN_NAME: <***>
      ADMIN_EMAIL: <***>
      TZ: Europe/Amsterdam
    restart: always
    ports:
     - 8080:80

  lime-db:
    container_name: lime-db
    image: mysql:5.7
    volumes:
     ...
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}"
      - "TZ=Europe/Amsterdam"
    restart: always
```

I already tried to use a different database, but it made no differences.
