### ISSUE TITLE
.env values from docker-compose don't seem to be passed to entrypoint for limesurvey app 

### ISSUE THREAD

**Issue by MarkErik** [martialblog/docker-limesurvey#41]
Hello,

I have set up my docker-compose file to use an .env file where I place sensitive values - specifically the database users and password. This way I can have all my code in GitHub, but keep the sensitive information in the .env file.
(I'll share my docker-compose file below the issue I am seeing)

The problem: I am seeing the following Warning in my Docker logs:
`limesurvey-db       | 2020-10-18 13:34:20 8 [Warning] Access denied for user 'limesurvey'@'172.24.0.3' (using password: YES)
`
Looking at the entrypoint.sh file, I can see that it using the default DB_USERNAME to try to access the database instead of the environment variables that I thought would be passed through.

I can confirm that my .env file is being read correctly as the Nginx container is signaling correctly for the creation of a HTTPS certificate from my proxy.

Thank you in advance for any help to get the limesurvey container to use the env values from the docker-compose file. 

Here is my docker-compose file:

```
version: "3.8"

services:

  limesurvey-app:
    image: martialblog/limesurvey:4-fpm-alpine
    volumes:
      - /tmp/upload/surveys:/var/www/html/upload/surveys
      - lime:/var/www/html
    container_name: limesurvey-app
    depends_on:
      - limesurvey-db
    env_file: .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    networks:
      - default
  
  limesurvey-nginx:
    image: nginx:latest
    container_name: limesurvey-nginx
    depends_on:
      - limesurvey-app
    restart: unless-stopped
    env_file: .env
    environment: 
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LEMAIL}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - lime:/var/www/html
      - ./logs-nginx:/var/log/nginx
    networks:
      - default
      - outside
  
  limesurvey-db:
    image: mariadb:latest
    container_name: limesurvey-db
    restart: unless-stopped
    volumes:
      - ./data/db-data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ['--default-authentication-plugin=mysql_native_password','--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci']
    networks:
      - default

networks:
  default:
    external:
      name: internal-limesurvey
  outside:
    external:
      name: connect-to-proxy

volumes:
  lime:

```
