### ISSUE TITLE
BASE_URL not working for admin 

### ISSUE THREAD

**Issue by amit-ch** [martialblog/docker-limesurvey#49]
I tried using the latest docker image and set base url to '/survey' and it works if I navigate to http://localhost/survey. However if I try admin url, its not following base url. Whenever I try to navigate to http://localhost/survey/admin It redirects with 301 to http://localhost/admin which returns 404. I have a requirement to serve limesurvey on a base path like https://server.com/base_path
Am I missing some config. Below is the docker-compose.yml I am using to try running locally.

```
version: "3.0"
services:
  limesurvey:
    image: martialblog/limesurvey
    restart: always
    volumes:
      - /tmp/upload/surveys:/var/www/html/upload/surveys
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.limesurvey.rule=Host(`localhost`)"
      # Allow request only from the predefined entry point named "web"
      - "traefik.http.routers.limesurvey.entrypoints=web"
      - "traefik.http.routers.limesurvey.rule=PathPrefix(`/survey`)"
      - "traefik.http.routers.limesurvey.middlewares=strip-limesurvey@docker"
      - "traefik.http.middlewares.strip-limesurvey.stripprefix.prefixes=/survey"
    links:
      - lime-db
    depends_on:
      - lime-db
    expose: 
      - "80"
    environment:
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=secret"
      - "ADMIN_PASSWORD=foobar"
      - "BASE_URL= /survey"
  lime-db:
    image: mysql:5.7
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
```
